site_name: Sustainability Documentation
repo_url: https://github.com/slowikr/mkdocs-example
theme:
  name: 'material'
  logo: 'images/logo.jpg'
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - toc.follow    
  palette:
    - scheme: cargill
extra_css:
  - stylesheets/cargill_mkdocs.css
use_directory_urls: false
markdown_extensions:
  - toc:
      title: On This Page
      toc_depth: 2-3
  - admonition
  - pymdownx.details
  - codehilite
  - attr_list
  - meta
  - pymdownx.emoji
  - pymdownx.progressbar
