site_name: Sustainability Documentation
repo_url: https://github.com/slowikr/mkdocs-example
theme:
  name: 'material'
  logo: 'images/logo.jpg'
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - toc.follow
  palette:
    - scheme: cargill
