site_name: Sustainability Documentation
repo_url: https://github.com/slowikr/mkdocs-example
theme:
  name: 'material'
  logo: 'images/logo.jpg'
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - toc.follow    
  palette:
    - scheme: cargill
extra_css:
  - stylesheets/cargill_mkdocs.css
use_directory_urls: false
markdown_extensions:
  - toc:
      title: On This Page
      toc_depth: 2-3
  - admonition
  - pymdownx.details
  - codehilite
  - attr_list
  - meta
  - pymdownx.emoji
  - pymdownx.progressbar
plugins:
    - search
    - mkdocs-video
    - glightbox
    - section-index
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://assets.adobedtm.com/47e3e446470b/4aea294d933b/launch-5c4c4fabc470.min.js'
